id: P4A034246
initial_creation_type: input
source_metadata:
  title: Chokling Tersar Series
  language: bo
  description: 'Texts related to the Chokling Tersar (mchog gling gter gsar), the
    New Treasures of Chokgyur Lingpa (1829–1870):'
  volume:
    101ed2c3aeed416882e8bf10052985c7:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    8ba335d2878547f091bf6142f7221f34:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    c571b304a7eb4b8b82c71bb0273320b1:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    b708f86fe9524f89a22b6fae766ba345:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    31a81e3726004361b4fd0969824c9fce:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    d55037d243f1447a92f51ad1651642b3:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    2236a9648dc24eb197c066718aa2cfa1:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    5f2ab05ed8d14bdeacf91e27fbc7d386:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Commentaries
    4621adb85c6d49bd89107e0ff37f11ea:
      title: The Lament of Rudra
      parent: Confession
    0f08c1273c764727be192d1187767341:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    2a04f4f629c940a6a6ecf82520342987:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Prayers
    e3cddd2d2c7d4ccd8690a85a39efbf3c:
      title: The Prayer in Six Vajra Lines
      parent: Prayers
    972f4fcedd0b41c4955f778d131cf774:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Prayers
    fc266527a09343b292cb5def99835f40:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Prayers
    de0f81647c6643f68854b8295d356b7f:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    bd3a98c97cdc49bf83449b197174bfdd:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    d942fb46562c413fa7f34245eb999ec8:
      title: Extremely Secret Unelaborate Daily Sādhana for the Heart Practice of
        the Great Demon-Slayer
      parent: Sādhanas
    414e673817ed4f659a27a30b88b6b1ab:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    d17c5a7f61954881b5ab2aa9bf91f3aa:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-03-01T03:13:53.997308'
last_modified_at: '2022-03-01T03:13:53.997311'
